services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm run dev"
